"""create quiz table

Revision ID: 940ef13e299c
Revises: c5e92b722a69
Create Date: 2024-05-13 15:28:44.235833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "940ef13e299c"
down_revision: Union[str, None] = "c5e92b722a69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quizzes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["quiz_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_quizzes_group_id"), "quizzes", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_quizzes_is_active"), "quizzes", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quizzes_is_active"), table_name="quizzes")
    op.drop_index(op.f("ix_quizzes_group_id"), table_name="quizzes")
    op.drop_table("quizzes")
    # ### end Alembic commands ###
